### Get all movies
GET http://localhost:3000/movies

### Get a specific movie by ID 
GET http://localhost:3000/movies/1

### Add a new movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "id": 4,
    "title": "All Quiet on the Western Front",
    "director": "Edward Berger",
    "year": 2022
}

### Update an existing movie
PUT http://localhost:3000/movies/4
Content-Type: application/json

{
    "title": "Tenet",
    "director": "Christopher Nolan",
    "year": 2020
}

### Delete a movie by ID
DELETE http://localhost:3000/movies/4